<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>Xapien.Task</PackageId>
    <Title>Xapien.Task</Title>
    <Authors>Z3LT1K09</Authors>
    <Company>Neem Technology</Company>
    <Description>Xapien is a data processing framework that aims to simplify the initial setup of a data processing application and allow developers to simply focus on the processing logic</Description>
    <PackageProjectUrl>https://github.com/ErickRV/Xapien</PackageProjectUrl>
    <PackageOutputPath>bin\Publish</PackageOutputPath>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.0" />
  </ItemGroup>

</Project>
